interview_topics = {
  "discussion of an outgoing, sociable person",
  "discussion of a compassionate person",
  "discussion of a disorganized person",
  "discussion of a relaxed person",
  "discussion of a person has few artistic interests",
  "discussion of a person has assertive personality",
  "discussion of a respectful person",
  "discussion of a lazy person",
  "discussion of a person stay optimistic after experiencing a setback",
  "discussion of a person curious about many different things",
  "discussion of a person rarely feels excited or eager",
  "discussion of a person finds fault with others",
  "discussion of a dependable, steady person",
  "discussion of a moody person",
  "discussion of an inventive person",
  "discussion of a quiet person",
  "discussion of a person feels little sympathy for others",
  "discussion of a systematic person",
  "discussion of a tense person",
  "discussion of a person fascinated by art, music, or literature",
  "discussion of a dominant person",
  "discussion of a person starts arguments with others",
  "discussion of a person has difficulty getting started on tasks",
  "discussion of a person feels secure, comfortable with self",
  "discussion of a person avoids intellectual, philosophical discussions",
  "discussion of a person less active than other people",
  "discussion of a person has a forgiving nature",
  "discussion of a careless person",
  "discussion of a emotionally stable, not easily upset person",
  "discussion of a person has little creativity",
  "discussion of a sometimes shy, introverted person",
  "discussion of a person helpful and unselfish with others",
  "discussion of a person keeps things neat and tidy",
  "discussion of a person worries a lot",
  "discussion of a person values art and beauty",
  "discussion of a person finds it hard to influence people",
  "discussion of a person sometimes rude to others",
  "discussion of an efficient person",
  "discussion of a person feels sad",
  "discussion of a deep thinker person",
  "discussion of a person full of energy",
  "discussion of a person suspicious of others’ intentions",
  "discussion of a reliable person",
  "discussion of a person keeps other's emotions under control",
  "discussion of a person has difficulty imagining things",
  "discussion of a talkative person",
  "discussion of a person leaves a mess",
  "discussion of a person rarely feels anxious or afraid",
  "discussion of a person thinks poetry and plays are boring",
  "discussion of a person prefers to have others take charge",
  "discussion of a polite person",
  "discussion of a persistent person",
  "discussion of a person feels depressed, blue",
  "discussion of a person has little interest in abstract ideas",
  "discussion of a person shows a lot of enthusiasm",
  "discussion of a person assumes the best about people",
  "discussion of a person sometimes behaves irresponsibly",
  "discussion of a temperamental person",
  "discussion of a person comes up with new ideas"
}